### PR TITLE
think 18

### PR DESCRIPTION
**Pull request by jesusmah**

### CODE REVIEW

**Comment by osowski** [comment]
This all looks good.  Just wanted to confirm that we have the `purplecompute` namespace created on the referenced ICP image once it starts up... IE we don't need / expect users to create it.

Other than that, looks good to go.

**Comment by jesusmah** [comment]
Yes, it is created out of the box. Still need to commit couple of things more based on Malu's  feedback

**Comment by osowski** [comment]
Looks good.  Merging now and we can sync up for final touches tomorrow.

**Review by osowski — COMMENTED** [review]
Looks good.  Let's sync up on what final pieces are needed for EOD Friday completion

**Pull request merged**
